package com.thg.accelerator.flatfish.transformer;


import com.thg.accelerator.flatfish.dto.UserDto;
import com.thg.accelerator.flatfish.entities.UserEntity;

public class Transformer {
    public static UserDto transformUserEntityToDto(UserEntity userEntity) {
        return new UserDto(
                userEntity.getName(),
                userEntity.getUserId(),
                userEntity.getDescription(),
                userEntity.getUserGender(),
                userEntity.getUserInsta());
    }

    public static UserEntity transformUserDtoToEntity(UserDto userDto) {
        UserEntity userEntity = new UserEntity();
        userEntity.setUserId(userDto.getEmail()); // Using email as userId
        userEntity.setName(userDto.getName());
        userEntity.setDescription(userDto.getDescription());
        userEntity.setUserGender(userDto.getUserGender());
        userEntity.setUserInsta(userDto.getUserInsta());

        return userEntity;
    }

    // TODO: Check if there needs to be an additional method for an incoming UserDto with no id (generated by UserEntity)
}
