package com.thg.accelerator.flatfish.transformer;


import com.thg.accelerator.flatfish.dto.UserDto;
import com.thg.accelerator.flatfish.entities.UserEntity;
import org.springframework.stereotype.Component;

@Component
public class Transformer {
    public static UserDto transformUserEntityToDto(UserEntity userEntity) {
        return new UserDto(
                userEntity.getUserId(),
                userEntity.getName(),
                userEntity.getAge(),
                userEntity.getDescription(),
                userEntity.getUserGender(),
                userEntity.getUserInsta(),
                userEntity.isSmoker());
    }

    public static UserEntity transformUserDtoToEntity(UserDto userDto) {
        UserEntity userEntity = new UserEntity();
        userEntity.setUserId(userDto.getUserId());
        userEntity.setName(userDto.getName());
        userEntity.setAge(userDto.getAge());
        userEntity.setDescription(userDto.getDescription());
        userEntity.setUserGender(userDto.getUserGender());
        userEntity.setUserInsta(userDto.getUserInsta());
        userEntity.setSmoker(userDto.isSmoker());

        return userEntity;
    }

    // TODO: Check if there needs to be an additional method for an incoming UserDto with no id (generated by UserEntity)
}
