export const locations = [
  "Ancoats and Beswick",
  "Ardwick",
  "Baguley",
  "Brooklands",
  "Burnage",
  "Charlestown",
  "Cheetham",
  "Chorlton",
  "Chorlton Park",
  "Deansgate",
  "City Wide",
  "Crumpsall",
  "Didsbury East",
  "Didsbury West",
  "Fallowfield",
  "Gorton and Abbey Hey",
  "Harpurhey",
  "Higher Blackley",
  "Hulme",
  "Levenshulme",
  "Longsight",
  "Miles Platting and Newton Heath",
  "Moss Side",
  "Moston",
  "Northenden",
  "Old Moat",
  "Piccadilly",
  "Rusholme",
  "Sharston",
  "Whalley Range",
  "Withington",
  "Woodhouse Park",
  "Salford",
  "Salford Quays",
];
