apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flatfish-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/(.*)
            pathType: Prefix
            backend:
              service:
                name: cockroachdbflatfishservice
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
